[2023-10-09T08:32:14.597+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_sql_dag.send_email_task manual__2023-10-07T03:09:45.603070+00:00 [queued]>
[2023-10-09T08:32:14.607+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_sql_dag.send_email_task manual__2023-10-07T03:09:45.603070+00:00 [queued]>
[2023-10-09T08:32:14.608+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-09T08:32:14.622+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_email_task> on 2023-10-07 03:09:45.603070+00:00
[2023-10-09T08:32:14.626+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2023-10-09T08:32:14.629+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_sql_dag', 'send_email_task', 'manual__2023-10-07T03:09:45.603070+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/etl_sql_dag.py', '--cfg-path', '/tmp/tmp_udhp0zy']
[2023-10-09T08:32:14.633+0000] {standard_task_runner.py:85} INFO - Job 986: Subtask send_email_task
[2023-10-09T08:32:14.672+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_sql_dag.send_email_task manual__2023-10-07T03:09:45.603070+00:00 [running]> on host e7b1a9bbd1dc
[2023-10-09T08:32:14.737+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_sql_dag' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T03:09:45.603070+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-07T03:09:45.603070+00:00'
[2023-10-09T08:32:14.739+0000] {logging_mixin.py:151} INFO - sending email
[2023-10-09T08:32:14.771+0000] {logging_mixin.py:151} INFO - success
[2023-10-09T08:32:14.772+0000] {logging_mixin.py:151} INFO - success
[2023-10-09T08:32:14.772+0000] {logging_mixin.py:151} INFO - None
[2023-10-09T08:32:14.773+0000] {logging_mixin.py:151} INFO - None
[2023-10-09T08:32:14.773+0000] {logging_mixin.py:151} INFO - None
[2023-10-09T08:32:14.775+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_sql_dag.py", line 228, in send_email
    em.set_content("Some tasks failed" + "\n" + "ETL process failed at " + str(datetime.now())
TypeError: can only concatenate str (not "NoneType") to str
[2023-10-09T08:32:14.787+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_sql_dag, task_id=send_email_task, execution_date=20231007T030945, start_date=20231009T083214, end_date=20231009T083214
[2023-10-09T08:32:14.800+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 986 for task send_email_task (can only concatenate str (not "NoneType") to str; 67)
[2023-10-09T08:32:14.842+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-09T08:32:14.857+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
