[2023-10-07T03:10:00.721+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_sql_dag.send_email_task manual__2023-10-07T03:09:45.603070+00:00 [queued]>
[2023-10-07T03:10:00.737+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_sql_dag.send_email_task manual__2023-10-07T03:09:45.603070+00:00 [queued]>
[2023-10-07T03:10:00.738+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-07T03:10:00.765+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): send_email_task> on 2023-10-07 03:09:45.603070+00:00
[2023-10-07T03:10:00.775+0000] {standard_task_runner.py:57} INFO - Started process 692 to run task
[2023-10-07T03:10:00.780+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_sql_dag', 'send_email_task', 'manual__2023-10-07T03:09:45.603070+00:00', '--job-id', '953', '--raw', '--subdir', 'DAGS_FOLDER/etl_sql_dag.py', '--cfg-path', '/tmp/tmp0a__y1a7']
[2023-10-07T03:10:00.785+0000] {standard_task_runner.py:85} INFO - Job 953: Subtask send_email_task
[2023-10-07T03:10:00.844+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_sql_dag.send_email_task manual__2023-10-07T03:09:45.603070+00:00 [running]> on host e7b1a9bbd1dc
[2023-10-07T03:10:00.934+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_sql_dag' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T03:09:45.603070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-07T03:09:45.603070+00:00'
[2023-10-07T03:10:00.938+0000] {logging_mixin.py:151} INFO - sending email
[2023-10-07T03:10:00.995+0000] {logging_mixin.py:151} INFO - success
[2023-10-07T03:10:00.997+0000] {logging_mixin.py:151} INFO - success
[2023-10-07T03:10:00.998+0000] {logging_mixin.py:151} INFO - None
[2023-10-07T03:10:01.000+0000] {logging_mixin.py:151} INFO - None
[2023-10-07T03:10:01.001+0000] {logging_mixin.py:151} INFO - None
[2023-10-07T03:10:01.005+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_sql_dag.py", line 228, in send_email
    em.set_content("Some tasks failed" + "\n" + "ETL process failed at " + str(datetime.now())
TypeError: can only concatenate str (not "NoneType") to str
[2023-10-07T03:10:01.038+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_sql_dag, task_id=send_email_task, execution_date=20231007T030945, start_date=20231007T031000, end_date=20231007T031001
[2023-10-07T03:10:01.069+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 953 for task send_email_task (can only concatenate str (not "NoneType") to str; 692)
[2023-10-07T03:10:01.115+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-07T03:10:01.141+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
